#!/bin/bash
echo "🔍 Testing Simple Fotoflo Sync App"
echo "=================================="
echo ""
echo "📁 App bundle structure:"
ls -la "Fotoflo Sync.app/Contents/"
echo ""
echo "📁 MacOS executable:"
ls -la "Fotoflo Sync.app/Contents/MacOS/"
echo ""
echo "📁 Resources:"
ls -la "Fotoflo Sync.app/Contents/Resources/"
echo ""
echo "🔧 Testing executable directly:"
echo "Running: Fotoflo Sync.app/Contents/MacOS/FotofloSync"
echo ""
"Fotoflo Sync.app/Contents/MacOS/FotofloSync"
